# Generated by Django 4.0.6 on 2022-08-04 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0004_alter_eventousuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(through='eventos.EventoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
