# Generated by Django 4.0.6 on 2022-08-08 22:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_eventousuario_evento_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventousuario',
            constraint=models.UniqueConstraint(fields=('evento', 'usuario'), name='unique_evento_usuarios'),
        ),
        migrations.AddConstraint(
            model_name='eventousuario',
            constraint=models.CheckConstraint(check=models.Q(('evento', django.db.models.expressions.F('usuario')), _negated=True), name='prevent_self_follow'),
        ),
    ]
