# Generated by Django 4.0.6 on 2022-08-04 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_remove_evento_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventoUsuario',
                'ordering': ['evento_id', 'usuario_id'],
            },
        ),
    ]
