# Generated by Django 4.0.6 on 2022-08-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_eventousuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventousuario',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
