# Generated by Django 4.0.6 on 2022-08-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0010_alter_eventousuario_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventousuario',
            name='evento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='eventousuario',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
