# Generated by Django 4.0.6 on 2022-08-08 22:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_eventousuario_unique_evento_usuarios_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventousuario',
            name='prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='eventousuario',
            constraint=models.CheckConstraint(check=models.Q(('evento', django.db.models.expressions.F('usuario')), _negated=True), name='prevent_repeat'),
        ),
    ]
