# Generated by Django 4.0.6 on 2022-08-23 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
                ('arch', models.FileField(upload_to='documents')),
                ('extension', models.CharField(choices=[('pdf', 'PDF'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('doc', 'DOC'), ('docx', 'DOCX'), ('png', 'PNG'), ('jpg', 'JPG'), ('txt', 'TXT'), ('ppt', 'PPT'), ('pptx', 'PPTX')], default='pdf', max_length=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'archivos',
                'ordering': ['nombre', 'fecha'],
            },
        ),
    ]
